# Generated by Django 4.1.5 on 2023-02-07 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8, message='La valeur doit contenir au moins 8 caracteres '), django.core.validators.MaxLengthValidator(8, 'La valeur doit avoir au max 8 caracteres ')]),
        ),
    ]
