# Generated by Django 4.1.5 on 2023-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_person_cin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': "Details de l'utilisateur"},
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='../users/imges/'),
        ),
    ]
