# Generated by Django 4.1.5 on 2023-02-07 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_dateevent_alter_event_nbrparticipants_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='la date est  invalide',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('dateEvent__gte', datetime.datetime(2023, 2, 7, 15, 41, 19, 119556))), name='la date est  invalide'),
        ),
    ]
