# Generated by Django 4.1.5 on 2023-02-14 11:58

import datetime
import django.core.validators
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_la date est  invalide_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Details des evenements'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Details Participation'},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='la date est  invalide',
        ),
        migrations.AlterField(
            model_name='event',
            name='dateEvent',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='nbrParticipants',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='la valeur doit etre positif ')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, validators=[events.models.TitleValid]),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('dateEvent__gte', datetime.datetime(2023, 2, 14, 12, 58, 44, 267527))), name='la date est  invalide'),
        ),
    ]
