# Generated by Django 4.1.5 on 2023-02-14 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_options_alter_participation_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='la date est  invalide',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('dateEvent__gte', datetime.datetime(2023, 2, 14, 13, 7, 37, 802534))), name='la date est  invalide'),
        ),
    ]
